/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.14
 * Generated at: 2019-06-07 06:56:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminPanelHeader_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--header-->\r\n");
      out.write("<!-- # for id of element . for class of element selection then name of subelement to which we want to apply css  -->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("  #collapse-target ul li a\r\n");
      out.write("  {\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    font-family: verdana;\r\n");
      out.write("    font-style: italic;\r\n");
      out.write("    color: white;\r\n");
      out.write("\r\n");
      out.write("  }\r\n");
      out.write(" #collapse-target ul li a:hover\r\n");
      out.write("  {\r\n");
      out.write("    border-bottom: 2px solid red;\r\n");
      out.write("  }\r\n");
      out.write("  #collapse-target ul li a:active\r\n");
      out.write("  {\r\n");
      out.write("    background-color: white;\r\n");
      out.write("  }\r\n");
      out.write("  #collapse-target ul li\r\n");
      out.write("  {\r\n");
      out.write("  opacity: .9;\r\n");
      out.write("  color: black;\r\n");
      out.write("  }\r\n");
      out.write("  #collapse-target ul \r\n");
      out.write("  {\r\n");
      out.write("    \r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("   .dropdown ul li\r\n");
      out.write("  {\r\n");
      out.write("    margin:15px;\r\n");
      out.write("  }\r\n");
      out.write("  .dropdown\r\n");
      out.write("  {\r\n");
      out.write("    margin:2px;\r\n");
      out.write("  }\r\n");
      out.write("</style>\r\n");
      out.write("<!--navbar-->\r\n");
      out.write("<nav class=\"navbar navbar-expand-sm  navbar-dark sticky-top\" style=\"background-color: #4d1d7c;font-family: Montserrat, sans-serif;min-height: 80px;z-index: 9999;border-bottom: 1px solid black;font-size: 12px !important;letter-spacing: 2px;color: white\">\r\n");
      out.write("\r\n");
      out.write("  <button class=\"navbar-toggler\" data-toggle=\"collapse\" data-target=\"#collapse-target\" >\r\n");
      out.write("    <!--this button is to make the below division whose id is collpase-target .as responsive ..span is a icon shown when screeen collapse -->\r\n");
      out.write("    <span class=\"navbar-toggler-icon\">\r\n");
      out.write("    </span>\r\n");
      out.write("  </button>\r\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"collapse-target\" style=\"margin-left: 30px\">\r\n");
      out.write("    \r\n");
      out.write("<div style=\"margin-right: 50px;left:0\">\r\n");
      out.write("  <h1>Admin Section</h1>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"dropdown\" >\r\n");
      out.write("  <button class=\"btn btn-primary dropdown-toggle\" type=\"button\" data-toggle=\"dropdown\">Add Information\r\n");
      out.write(" </button>\r\n");
      out.write("  <ul class=\"dropdown-menu\" style=\"background-color: green;font-size: 12px;\">\r\n");
      out.write("    <!--<li><a href=\"#\">View Campuses</a></li>-->\r\n");
      out.write("      <li onclick=\"javascript:addCountryFunction('block')\"><a href=\"#\">Add Country</a></li>\r\n");
      out.write("      <li onclick=\"javascript:addStateFunction('block')\"><a href=\"#\">Add State</a></li>\r\n");
      out.write("      <li onclick=\"javascript:addCityFunction('block')\"><a href=\"#\">Add City</a></li>\r\n");
      out.write("    <li onclick=\"javascript:addCampusFunction('block')\"><a href=\"#\">Add Campus</a></li>\r\n");
      out.write("    <li onclick=\"javascript:addStreamFunction('block')\"><a href=\"#\">Add Stream</a></li>\r\n");
      out.write("    <li onclick=\"javascript:addBranchFunction('block')\"><a href=\"#\">Add Branch</a></li>\r\n");
      out.write("    <li onclick=\"javascript:addBranchSeatsFunction('block')\"><a href=\"#\">Add Branch Seats</a></li>\r\n");
      out.write("\r\n");
      out.write("  </ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--\r\n");
      out.write("<div class=\"dropdown\" >\r\n");
      out.write("  <button class=\"btn btn-primary dropdown-toggle\" type=\"button\" data-toggle=\"dropdown\">Stream\r\n");
      out.write(" </button>\r\n");
      out.write("  <ul class=\"dropdown-menu\" style=\"background-color: green;font-size: 12px;\">\r\n");
      out.write("\r\n");
      out.write("    <li onclick=\"javascript:addStreamFunction('block')\"><a href=\"#\">Add Stream</a></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"dropdown\" >\r\n");
      out.write("  <button class=\"btn btn-primary dropdown-toggle\" type=\"button\" data-toggle=\"dropdown\">Branch\r\n");
      out.write(" </button>\r\n");
      out.write("  <ul class=\"dropdown-menu\" style=\"background-color: green;font-size: 12px;\">\r\n");
      out.write("\r\n");
      out.write("    <li onclick=\"javascript:addBranchFunction('block')\"><a href=\"#\">Add Branch</a></li>\r\n");
      out.write("    <li onclick=\"javascript:addBranchSeatsFunction('block')\"><a href=\"#\">Add Branch Seats</a></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"dropdown\" >\r\n");
      out.write("  <button class=\"btn btn-primary dropdown-toggle\" type=\"button\" data-toggle=\"dropdown\">City\r\n");
      out.write(" </button>\r\n");
      out.write("  <ul class=\"dropdown-menu\" style=\"background-color: green;font-size: 12px;\">\r\n");
      out.write("   \r\n");
      out.write("    <li onclick=\"javascript:addCityFunction('block')\"><a href=\"#\">Add City</a></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"dropdown\" >\r\n");
      out.write("  <button class=\"btn btn-primary dropdown-toggle\" type=\"button\" data-toggle=\"dropdown\">State\r\n");
      out.write(" </button>\r\n");
      out.write("  <ul class=\"dropdown-menu\" style=\"background-color: green;font-size: 12px;\">\r\n");
      out.write("  \r\n");
      out.write("    <li onclick=\"javascript:addStateFunction('block')\"><a href=\"#\">Add State</a></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"dropdown\" >\r\n");
      out.write("  <button class=\"btn btn-primary dropdown-toggle\" type=\"button\" data-toggle=\"dropdown\">Country\r\n");
      out.write(" </button>\r\n");
      out.write("  <ul class=\"dropdown-menu\" style=\"background-color: green;font-size: 12px;\">\r\n");
      out.write("   <li><a href=\"#\">View Countries</a></li>\r\n");
      out.write("    <li onclick=\"javascript:addCountryFunction('block')\"><a href=\"#\">Add Country</a></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--for search\r\n");
      out.write("<div id=\"aaabbb\" style=\"display: none;background-color: black;z-index: 100001 !important;position: absolute;min-height: 500px\" class=\"container col-sm-12\">\r\n");
      out.write("<div id=\"searchDivision\" class=\"container-fluid col-sm-7\" style=\"background-color: #ed9393\">\r\n");
      out.write("  \r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("-->\r\n");
      out.write("<!--navbar-->\r\n");
      out.write("<!--header-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("  //add campus division display none or block\r\n");
      out.write("  function addCampusFunction(dsply)\r\n");
      out.write("  {  \r\n");
      out.write("    document.getElementById(\"addCampus\").style.display=dsply;\r\n");
      out.write("    document.getElementById(\"addStream\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addBranch\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addCity\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addState\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addBranchSeats\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addCountry\").style.display='none';\r\n");
      out.write("    clearAddCampusForm(); \r\n");
      out.write("    getCountryList('addCampusFormCountryDropDown');\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  function addStreamFunction(dsply)\r\n");
      out.write("  {\r\n");
      out.write("    document.getElementById(\"addCampus\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addStream\").style.display=dsply;\r\n");
      out.write("    document.getElementById(\"addBranch\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addCity\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addState\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addCountry\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addBranchSeats\").style.display='none';\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  function addBranchFunction(dsply)\r\n");
      out.write("  {\r\n");
      out.write("    document.getElementById(\"addCampus\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addStream\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addBranch\").style.display=dsply;\r\n");
      out.write("    document.getElementById(\"addBranchSeats\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addCity\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addState\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addCountry\").style.display='none';\r\n");
      out.write("    getStreamList('addBranchFormStreamDropDown');\r\n");
      out.write("  }\r\n");
      out.write("  function addBranchSeatsFunction(dsply)\r\n");
      out.write("  {\r\n");
      out.write("    document.getElementById(\"addCampus\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addStream\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addBranchSeats\").style.display=dsply;\r\n");
      out.write("    document.getElementById(\"addBranch\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addCity\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addState\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addCountry\").style.display='none';\r\n");
      out.write("    getCampusList('addBranchSeatsFormCampusDropDown');\r\n");
      out.write("    getStreamList('addBranchSeatsFormStreamDropDown');\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  function addCityFunction(dsply)\r\n");
      out.write("  {\r\n");
      out.write("    document.getElementById(\"addCampus\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addStream\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addBranch\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addCity\").style.display=dsply;\r\n");
      out.write("    document.getElementById(\"addBranchSeats\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addState\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addCountry\").style.display='none';\r\n");
      out.write("    getCountryList('addCityFormCountryDropDown');\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  function addStateFunction(dsply)\r\n");
      out.write("  {\r\n");
      out.write("    document.getElementById(\"addCampus\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addStream\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addBranch\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addCity\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addState\").style.display=dsply;\r\n");
      out.write("    document.getElementById(\"addBranchSeats\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addCountry\").style.display='none';\r\n");
      out.write("    getCountryList('addStateFormCountryDropDown');//for adding data in country dropdown\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  function addCountryFunction(dsply)\r\n");
      out.write("  {\r\n");
      out.write("    document.getElementById(\"addCountry\").style.display=dsply;\r\n");
      out.write("    document.getElementById(\"addBranchSeats\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addCampus\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addStream\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addBranch\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addCity\").style.display='none';\r\n");
      out.write("    document.getElementById(\"addState\").style.display='none';\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("function clearAddCampusForm(formId)\r\n");
      out.write("{\r\n");
      out.write("  var d=document.getElementById('addCampusFormCountryDropDown');\r\n");
      out.write("  while(d.children[1]) \r\n");
      out.write("  {\r\n");
      out.write("    d.removeChild(d.children[1]);\r\n");
      out.write("  }\r\n");
      out.write("  d=document.getElementById('addCampusFormStateDropDown');\r\n");
      out.write("  while(d.children[1]) \r\n");
      out.write("  {\r\n");
      out.write("    d.removeChild(d.children[1]);\r\n");
      out.write("  }\r\n");
      out.write("  d=document.getElementById('addCampusFormCityDropDown');\r\n");
      out.write("  while(d.children[1]) \r\n");
      out.write("  {\r\n");
      out.write("    d.removeChild(d.children[1]);\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
