/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.14
 * Generated at: 2019-02-18 22:09:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class i_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<title></title>\r\n");
      out.write("\t <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction makeid( length ) {\r\n");
      out.write("    \r\n");
      out.write("    var str = \"\";\r\n");
      out.write("    for ( ; str.length < length; str += Math.random().toString( 36 ).substr( 2 ) );\r\n");
      out.write("    return str.substr( 0, length );\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction createBox(parent)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar pp=makeid(5);\r\n");
      out.write("\t\t\t//var r = Math.random().toString(36).substring(5);\r\n");
      out.write("\tvar mask=document.createElement(\"div\");\r\n");
      out.write("\tmask.classList.add(\"media\");\r\n");
      out.write("\tmask.classList.add(\"p-3\");\r\n");
      out.write("\t//mask.classList.add(\"border\");\r\n");
      out.write("\tvar profile=document.createElement('img');\r\n");
      out.write("\tprofile.setAttribute(\"src\",\"khandelwal.png\");\r\n");
      out.write("\tprofile.style=\"width:60px\";\r\n");
      out.write("\tprofile.classList.add('rounded-circle');\r\n");
      out.write("\tmask.appendChild(profile);\r\n");
      out.write("\tvar body=document.createElement('div');\r\n");
      out.write("\tbody.classList.add(\"media-body\");\r\n");
      out.write("\tvar bodyId=\"b\"+pp;\r\n");
      out.write("\tbody.setAttribute(\"id\",bodyId);\r\n");
      out.write("\tvar heading=document.createElement('h4');\r\n");
      out.write("\theading.innerHTML=\"John DoeLorem ipsum dolor sit ametLorem ipsum dolor sit ametLorem ipsum dolor sit ametLorem ipsum color sit amet\";\r\n");
      out.write("\tvar time=document.createElement('small');\r\n");
      out.write("\ttime.innerHTML=\"posted on\";\r\n");
      out.write("\tvar date=document.createElement('i');\r\n");
      out.write("\tdate.innerHTML=\"19 feb 2019\";\r\n");
      out.write("\ttime.appendChild(date);\r\n");
      out.write("\theading.appendChild(time);\r\n");
      out.write("\tbody.appendChild(heading);\r\n");
      out.write("\tvar content=document.createElement('p');\r\n");
      out.write("\tcontent.innerHTML=\"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\";\r\n");
      out.write("\tbody.appendChild(content);\r\n");
      out.write("\tvar replyButton=document.createElement('label');\r\n");
      out.write("\treplyButton.style=\"font-weight: bold;color: skyblue;cursor: pointer;\";\r\n");
      out.write("\treplyButton.innerHTML=\"reply\";\r\n");
      out.write("\tvar replyButtonId=\"replyButton\"+pp;\r\n");
      out.write("\treplyButton.setAttribute(\"id\",replyButtonId);\r\n");
      out.write("\treplyButton.onclick=function()\r\n");
      out.write("        {\r\n");
      out.write("          $('#'+commentFormId).show(500);\r\n");
      out.write("          $('#'+replyButtonId).css(\"display\",\"none\");\r\n");
      out.write("        };\r\n");
      out.write("\tbody.appendChild(replyButton);\r\n");
      out.write("\t//comment form\r\n");
      out.write("\tvar commentForm=document.createElement('div');\r\n");
      out.write("\tcommentFormId=\"commentForm\"+pp;\r\n");
      out.write("\tcommentForm.setAttribute(\"id\",commentFormId);\r\n");
      out.write("\tcommentForm.style=\"display:none\";\r\n");
      out.write("\tvar textarea=document.createElement('textarea');\r\n");
      out.write("\ttextarea.style=\"resize: none;border:none;\";\r\n");
      out.write("\ttextarea.classList.add(\"form-control\");\r\n");
      out.write("\ttextarea.setAttribute(\"rows\",5);\r\n");
      out.write("\ttextareaId=\"comment\"+pp;\r\n");
      out.write("\ttextarea.setAttribute(\"id\",textareaId);\r\n");
      out.write("\ttextarea.setAttribute(\"name\",\"comment\");\r\n");
      out.write("\ttextarea.setAttribute(\"placeholder\",\"write reply here..\");\r\n");
      out.write("\tvar postCommentButton=document.createElement('button');\r\n");
      out.write("\tpostCommentButton.classList.add(\"btn\");\r\n");
      out.write("\tpostCommentButton.classList.add(\"btn-primary\"); \r\n");
      out.write("\tpostCommentButton.style=\"margin-left: 3px;margin-top: 3px;\";\r\n");
      out.write("\tpostCommentButton.innerHTML=\"post comment\";\r\n");
      out.write("\tpostCommentButton.onclick=function()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tcreateBox(bodyId);\r\n");
      out.write("\t\tdocument.getElementById(textareaId).value=\"\";\r\n");
      out.write("      $('#'+commentFormId).hide(500);\r\n");
      out.write("      $('#'+replyButtonId).css(\"display\",\"block\");\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\tvar cancelButton=document.createElement('button');\r\n");
      out.write("\tcancelButton.classList.add(\"btn\");\r\n");
      out.write("\tcancelButton.classList.add(\"btn-danger\");\r\n");
      out.write("\tcancelButton.style=\"margin-left: 3px;margin-top: 3px;\";\r\n");
      out.write("\tcancelButton.innerHTML=\"cancel\";\r\n");
      out.write("\tvar cancelButtonId=\"cancelButton\"+pp;\r\n");
      out.write("\tcancelButton.setAttribute(\"id\",cancelButtonId);\r\n");
      out.write("\tcancelButton.onclick=function(){\r\n");
      out.write("      document.getElementById(textareaId).value=\"\";\r\n");
      out.write("      $('#'+commentFormId).hide(500);\r\n");
      out.write("      $('#'+replyButtonId).css(\"display\",\"block\");\r\n");
      out.write("\r\n");
      out.write("    };\r\n");
      out.write("\tcommentForm.appendChild(textarea);\r\n");
      out.write("\tcommentForm.appendChild(postCommentButton);\r\n");
      out.write("\tcommentForm.appendChild(cancelButton);\r\n");
      out.write("\r\n");
      out.write("\t//comment form\r\n");
      out.write("\tbody.appendChild(commentForm);\r\n");
      out.write("\tmask.appendChild(body);\r\n");
      out.write("\r\n");
      out.write("\tvar space=document.createElement('div');\r\n");
      out.write("\tspace.style=\"height:15px\";\r\n");
      out.write("\tvar x=document.getElementById(parent);\r\n");
      out.write("\tx.appendChild(space);\r\n");
      out.write("\tx.appendChild(mask);\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container mt-3 border\" id=\"x\">\r\n");
      out.write("   \r\n");
      out.write("  </div>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<a href=\"javascript:createBox('x')\">create</a>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
